# Generated by Django 2.0.6 on 2019-05-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sets',
            field=models.ManyToManyField(related_name='words', to='core.Set'),
        ),
    ]
