# Generated by Django 2.0.6 on 2018-06-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180603_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Setsandword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sets')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='setsandword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Words'),
        ),
    ]
