# Generated by Django 2.0.6 on 2018-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180603_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setsandword',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setsandword',
            name='word',
        ),
        migrations.AddField(
            model_name='words',
            name='sets',
            field=models.ManyToManyField(related_name='words', to='core.Sets'),
        ),
        migrations.DeleteModel(
            name='Setsandword',
        ),
    ]
